[package]
name = "agglayer-primitives"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
alloy-primitives = { version = "0.8.15", features = ["serde", "k256"] }
k256 = "0.13.4"
serde.workspace = true

[lints]
workspace = true
