name: Util | Unit tests

runs:
  using: composite
  steps:
    - name: Checkout sources
      uses: actions/checkout@v4

    - name: Install toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Set up rust cache
      uses: Swatinem/rust-cache@v2
      with:
        save-if: ${{ github.ref == 'refs/heads/main' }}

    - uses: taiki-e/install-action@nextest
    - uses: taiki-e/install-action@protoc

    - name: Install Anvil
      uses: foundry-rs/foundry-toolchain@v1

    - name: Test
      shell: bash
      run: cargo nextest run --workspace && cargo test --doc --workspace
