[env]
CONTRACT_VERSION = "12.2.3"
CONTRACT_REPO = "https://api.github.com/repos/agglayer/agglayer-contracts"
CONTRACT_IMAGE_REPO = "ghcr.io/agglayer/agglayer-contracts"

[tasks.contracts]
description = "Download and update the contracts of agglayer-contracts"
dependencies = ["contracts-downloader"]

[tasks.contracts-downloader]
dependencies = [
    { name = "contracts-download-PolygonRollupManager" },
    { name = "contracts-download-PolygonZkEVM" },
    { name = "contracts-download-PolygonZkEVMGlobalExitRootV2" },
    { name = "contracts-download-AggchainBase" },
    { name = "contracts-download-AggLayerGateway" },
]

[tasks.contracts-download-AggLayerGateway]
env = { "CONTRACT_SOURCE" = "AgglayerGateway.json", "CONTRACT_OUTPUT" = "AggLayerGateway.json" }
run_task = "contracts-download"

[tasks.contracts-download-AggchainBase]
env = { "CONTRACT_SOURCE" = "AggchainBase.json", "CONTRACT_OUTPUT" = "AggchainBase.json" }
run_task = "contracts-download"

[tasks.contracts-download-PolygonRollupManager]
env = { "CONTRACT_SOURCE" = "PolygonRollupManager.json", "CONTRACT_OUTPUT" = "PolygonRollupManager.json" }
run_task = "contracts-download"

[tasks.contracts-download-PolygonZkEVM]
env = { "CONTRACT_SOURCE" = "PolygonZkEVM.json", "CONTRACT_OUTPUT" = "PolygonZkEVM.json" }
run_task = "contracts-download"

[tasks.contracts-download-PolygonZkEVMGlobalExitRootV2]
env = { "CONTRACT_SOURCE" = "PolygonZkEVMGlobalExitRootV2.json", "CONTRACT_OUTPUT" = "PolygonZkEVMGlobalExitRootV2.json" }
run_task = "contracts-download"

[tasks.contracts-download]
condition = { env_set = ["CONTRACT_SOURCE", "CONTRACT_OUTPUT", "GITHUB_TOKEN"] }
description = "Download the contract of agglayer-contracts"
cwd = "crates/agglayer-contracts"
command = "curl"
args = [
    "-HAuthorization: token ${GITHUB_TOKEN}",
    "-HAccept: application/vnd.github.v4.raw",
    "-Ls",
    "--output",
    "./src/contracts/${CONTRACT_OUTPUT}",
    "--proto",
    "=https",
    "${CONTRACT_REPO}/contents/compiled-contracts/${CONTRACT_SOURCE}?ref=v${CONTRACT_VERSION}",
]

[tasks.integration-l1-image]
category = "INTEGRATIONS - PREPARE"
description = "Pull and tag the L1 image for integration tests"
script = '''
set -eu

IMAGE_TAG="${CONTRACT_IMAGE_TAG:-${CONTRACT_VERSION}-all}"

docker pull "${CONTRACT_IMAGE_REPO}:${IMAGE_TAG}"
docker tag "${CONTRACT_IMAGE_REPO}:${IMAGE_TAG}" hermeznetwork/geth-zkevm-contracts
'''
