version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"

    groups:
      provers:
        applies-to: version-updates
        patterns:
          - "aggchain-proof-*"
          - "aggkig-prover"
          - "aggkit-prover-*"
          - "agglayer-prover"
          - "agglayer-prover-*"
          - "proposer-*"
          - "prover-*"

      sp1:
        applies-to: version-updates
        patterns:
          - "sp1-*"

      external:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
