[package]
name = "agglayer-grpc-server"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
agglayer-grpc-types = { path = "../agglayer-grpc-types" }
tonic.workspace = true

[lints]
workspace = true
