[env]
RUST_VERSION = "1.81.0"
SP1_VERSION = "v1.81.0"
SP1_TOOLCHAIN_HASH_aarch64 = "68bc4a29237e2eb862da36324d19cf835bb93f45106ad206ba17836fb7862f32"
SP1_TOOLCHAIN_HASH_x86 = "68bc4a29237e2eb862da36324d19cf835bb93f45106ad206ba17836fb7862f32"
SP1_ARCH = "${CARGO_MAKE_RUST_TARGET_ARCH}"

[tasks.pp-elf]
description = "Install pessimistic proof ELF file"
dependencies = ["pp-elf-build"]
cwd = "crates/pessimistic-proof-program"
command = "cp"
args = [
    "target/riscv32im-succinct-zkvm-elf/release/pessimistic-proof-program",
    "elf/riscv32im-succinct-zkvm-elf",
]

[tasks.pp-elf-build]
args = [
    "run",
    "--rm",
    "--env",
    "CARGO_ENCODED_RUSTFLAGS=-C\u001fpasses=loweratomic\u001f-C\u001flink-arg=-Ttext=0x00200800\u001f-C\u001fpanic=abort",
    "-v${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}:/sp1/source",
    "-w/sp1/source/crates/pessimistic-proof-program",
    "sp1:ppbuild",
    "cargo",
    "build",
    "--target=riscv32im-succinct-zkvm-elf",
    "--release",
    "--locked",
    "-vv",
]
description = "Compile pessimistic proof ELF file"
dependencies = ["sp1-toolchain-image"]
command = "docker"

[tasks.sp1-toolchain-shell]
description = "Drop into an interactive shell in sp1 build environment image"
dependencies = ["sp1-toolchain-image"]
command = "docker"
args = [
    "run",
    "--rm",
    "-it",
    "-v${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}:/sp1/source",
    "sp1:ppbuild",
]

[tasks.sp1-toolchain-image-config]
script_runner = "@duckscript"
script = '''
arch = get_env SP1_ARCH
sha_arch = get_env SP1_TOOLCHAIN_HASH_${arch}

set_env SP1_TOOLCHAIN_HASH ${sha_arch}
'''

[tasks.sp1-toolchain-image]
dependencies = ["sp1-toolchain-image-config"]
description = "Build a docker image with sp1 build environment"
command = "docker"
args = [
    "build",
    "--build-arg=RUST_VERSION",
    "--build-arg=SP1_VERSION",
    "--build-arg=SP1_TOOLCHAIN_HASH",
    "--build-arg=SP1_ARCH",
    "-tsp1:ppbuild",
    "-f./build/sp1-toolchain/Dockerfile",
    "./build/sp1-toolchain",
]
