[package]
name = "agglayer-grpc-client"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
agglayer-grpc-types.workspace = true
tonic.workspace = true

[lints]
workspace = true
