[book]
authors = ["Agglayer contributors"]
language = "en"
src = "src"
title = "Agglayer Knowledge Base"

[output.html]
git-repository-url = "https://github.com/agglayer/agglayer"
edit-url-template = "https://github.com/agglayer/agglayer/edit/main/docs/knowledge-base/{path}"
additional-js = ["rustdoc-link.js"]
