[package]
name = "pessimistic-proof-utils"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
pessimistic-proof = { path = "../pessimistic-proof" }
base64 = "0.22.0"
reth-primitives = { git = "https://github.com/sp1-patches/reth", default-features = false, branch = "sp1-reth" }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["arbitrary_precision"] }
serde_with = { version = "3" }
tiny-keccak = { git = "https://github.com/sp1-patches/tiny-keccak", branch = "patch-v2.0.2", features = [
    "keccak",
] }

[dev-dependencies]
rand = "0.8.5"
