[test-groups]
resource-limited = { max-threads = 4 }
serial-integration = { max-threads = 1 }

[profile.default]
default-filter = "not package(integrations)"

[profile.integrations]
default-filter = "package(integrations)"
threads-required = 3

[[profile.integrations.overrides]]
filter = 'package(integrations)'
test-group = 'serial-integration'
