name: Checking commit message

on:
  push:
    branches:
      - main
  merge_group:

permissions:
  contents: read
  pull-requests: read
  statuses: write

jobs:
  commits:
    name: Validate PR commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v6
