name: Test - ELF

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"
  workflow_dispatch:
    branches:
      - "**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_id || github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  CARGO_TERM_COLOR: always

jobs:
  check_elf:
    runs-on: ubuntu-latest-16-cores
    name: ELF Checking
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Define source checksum
        run: |
          echo CHECKSUM="$(sha256sum crates/pessimistic-proof-program/elf/riscv32im-succinct-zkvm-elf | awk '{ print $1 }')" >> "$GITHUB_ENV"

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Set up rust cache
        uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - uses: taiki-e/install-action@protoc

      - name: Define vKey
        run: |
          echo ORIGINAL_VKEY="$(cargo run -p agglayer -- vkey)" >> "$GITHUB_ENV"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: taiki-e/install-action@protoc

      - name: Install cargo-make
        run: cargo install --debug --locked cargo-make

      - run: cargo make pp-elf

      - name: ELF is up to date
        run: diff <(sha256sum crates/pessimistic-proof-program/elf/riscv32im-succinct-zkvm-elf | awk '{ print $1 }') <( echo $CHECKSUM )

      - name: Check vKey
        run: |
          CALCULATED_VKEY=$(cargo run -p agglayer -- vkey)
          echo "Commited vKey=$ORIGINAL_VKEY"
          echo "Calculated vKey=$CALCULATED_VKEY"
          diff <(echo $CALCULATED_VKEY) <( echo $ORIGINAL_VKEY )
